language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php:
      - 7.0
      - hhvm-nightly

cache:
    - apt

install:
  - composer self-update
  - composer --prefer-source install

script:
  - ./bin/phpsa check -vvv ./tests